server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 valid=10s ipv6=off;

    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

    location = /api {
        return 308 /api/;
    }

    location /api/ {
        set $archival_api_upstream "${ARCHIVAL_API_PROXY_PASS}";
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $archival_api_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_request_buffering off;
        proxy_read_timeout 7200s;
        proxy_send_timeout 7200s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
